server:
  port: 8080

spring:
#  application:
#    name: nep-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/nep/admin/**
        - id: grid-service
          uri: lb://grid-service
          predicates:
            - Path=/nep/grid/**
        - id: supervisor-service
          uri: lb://supervisor-service
          predicates:
            - Path=/nep/supervisor/**
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/nep/statistics/**
        - id: aqi-service
          uri: lb://aqi-service
          predicates:
            - Path=/nep/aqi/**
        - id: aqifeedback-service
          uri: lb://aqi-feedback-service
          predicates:
            - Path=/nep/aqifeedback/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=nep/gridcity/**,nep/gridprovince/**
  main:
    web-application-type: reactive
#  datasource:
#    druid:
#      #MySQL
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/nep?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#      username: root
#      password: FB20020910
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      max-wait: 6000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: false
#      web-stat-filter:
#        enabled: false


#nep:
#  jwt:
#    location: classpath:nep.jks
#    alias: nep
#    password: 123
#    tokenTTL: 30m
#  auth:
#    excludePaths:
#      - /search/**
#      - /users/login
#      - /items/**
#      - /hi