server:
  port: 8084
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:9000
      http-method-specify: true
  redis:
    host: localhost
    port: 6379
    database: 0
#spring:
#  application:
#    name: statistics-service
#  datasource:
#    druid:
#      #MySQL
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/nep?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#      username: root
#      password: FB20020910
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      max-wait: 6000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: false
#      web-stat-filter:
#        enabled: false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848


#mybatis-plus:
#  configuration:
#    cache-enabled: true